USE WebHosting;
GO

CREATE OR ALTER PROCEDURE usp_DeleteAllData
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM IntrariFactura;
	DELETE FROM Facturi;
	DBCC CHECKIDENT('Facturi', RESEED, 0);
	DELETE FROM VPS;
	DBCC CHECKIDENT('VPS', RESEED, 0);
	DELETE FROM Recenzii;
	DBCC CHECKIDENT('Recenzii', RESEED, 0);
	DELETE FROM PlaciRetea;
	DBCC CHECKIDENT('PlaciRetea', RESEED, 0);
	DELETE FROM Memorii;
	DBCC CHECKIDENT('Memorii', RESEED, 0);
	DELETE FROM Stocare;
	DBCC CHECKIDENT('Stocare', RESEED, 0);
	DELETE FROM Procesoare;
	DBCC CHECKIDENT('Procesoare', RESEED, 0);
	DELETE FROM Servere;
	DBCC CHECKIDENT('Servere', RESEED, 0);
	DELETE FROM Producatori;
	DBCC CHECKIDENT('Producatori', RESEED, 0);
	DELETE FROM Clienti;
	DBCC CHECKIDENT('Clienti', RESEED, 0);
	DELETE FROM FirmeHosting;
	DBCC CHECKIDENT('FirmeHosting', RESEED, 0);
END;
GO